name: Repository Dispatch
on:
  repository_dispatch:
    types: [texecom2mqtt-publish]
jobs:
  update_version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: python update.py ${{ github.event.client_payload.version }}
      - uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: 'Bump version to ${{ github.event.client_payload.version }}'
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.client_payload.version }}
          release_name: Release v${{ github.event.client_payload.version }}
          commitish: master
          draft: false
          prerelease: false
