name: Repository Dispatch
on:
  repository_dispatch:
    types: [texecom2mqtt-publish]
jobs:
  update_version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: python update.py ${{ github.event.client_payload.version }}
      - uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: 'Bump version to ${{ github.event.client_payload.version }}'
